Add CSIDriver
red-hat-storage/lvm-operator pull request #11
Opened 2021-12-07 18:16 UTC by jmolmo

Not sure about several things...

- Should we use a "unit" for the CSIDriver? If the answer is yes, we will need to solve cross reference imports ( "controllers" needs "CSIDriver", and "CSIDriver" needs "controllers", we will have the same problem with other "pkgs".. (Not sure if i understand well the pattern to use the interface for units in the `lvmcluster_controller`)

- Maybe it would be useful a customized `context` with more things .. include the `clientset `can be useful for lot of things

Signed-off-by: Juan Miguel Olmo Martínez <jolmomar@redhat.com>

2021-12-08 02:00 UTC, sp98 requested changes
unit tests?

2021-12-08 03:32 UTC, leelavg commented
@jmolmo 

- a lot has to be changed, i'll try to explain the best I can
Some good to know info:
1. Every unit (vgmanager, csicontroller, csinode, csidriver) should implement the interface `resourceManager` to be cleaner for any extensions
2. If any unit doesn't want to reconcile any method (or a specific piece of) it can be left empty (ex. csidriver resource doesn't need an update)


> Should we use a "unit" for the CSIDriver?
1. yes

> "controllers" needs "CSIDriver", and "CSIDriver" needs "controllers"
1. nope, we can get away without deploying CSIDriver resource at all 😅 
2. it's presence only informs k8s that this driver supports/needs these (attachRequired, podInfoOnMount, storageCapacity) functionalities
3. in it's absence it gets the info from one of the controller plugin RPC calls

- Why all this hassle if it's not mandatory?
1. not explaining the detail, we are deploying the CSIDriver just to save a single RPC call and it's roundtrip by setting `attachRequired` to `false`

- Reg PR
1. I was told to use `controllerutil.CreateOrUpdate` for resource creation and utilise controller-runtime client interface https://github.com/kubernetes-sigs/controller-runtime/blob/3ffc700bc2a37c97acd6ce3a03c3526df8a5e489/pkg/client/interfaces.go#L100-L110
2. Owner ref will not work on this resource so main reconciler will set a finalizer on the CR and invokes CSIDriver resource deletion
3. No, we don't need to set `resourceVersion` and it may not work I guess, afaik it's for client & server confirmation that the resource isn't  mutated while we are updating it
4. We are supporting only single CR and better use the logging field available in the main reconciler

Let me know if any of the points doesn't make sense

2021-12-08 03:45 UTC, rohantmp requested changes
Here is an example from ocs-operator where we took the resourceManager idea from: 
The interface: https://github.com/red-hat-storage/ocs-operator/blob/bf0946e7b4d47b799d209c491f0fcfbd71a4295c/controllers/storagecluster/reconcile.go#L33

A list of implementations: https://github.com/red-hat-storage/ocs-operator/blob/bf0946e7b4d47b799d209c491f0fcfbd71a4295c/controllers/storagecluster/reconcile.go#L352

clients and loggers are available in the first argument of ensureCreated(): https://github.com/red-hat-storage/lvm-operator/blob/a72ebd4a8fb3d478ca6610216264956b3ed52a65/controllers/lvmcluster_controller.go#L126

2021-12-08 03:45 UTC, rohantmp commented on pkg/csi/csidriver.go
> +	logger = capnslog.NewPackageLogger("github.com/red-hat-storage/lvm-operator", "csi")
let's use the controller-runtime logger? `LVMClusterReconciler.Log`?

2021-12-08 03:45 UTC, rohantmp commented on pkg/util/k8s/k8s.go
> +func GetClientSet(ctx context.Context) (*kubernetes.Clientset, error) {
Let's use the controller-runtime client, it reads from a cache and you supports all runtime.Objects. `LVMClusterReconciler.Client.Create/Update/Delete`

2021-12-09 12:11 UTC, jmolmo commented
> * a lot has to be changed, i'll try to explain the best I can, some good to know info:

Perfectly explained @leelavg , Thank you for take the time to explain!!. I think we can close this PR in favor of your PR (https://github.com/red-hat-storage/lvm-operator/pull/13).

2021-12-09 12:13 UTC, jmolmo commented
@rohantmp : Thank you for the multiple references. !! :-)

2021-12-09 12:14 UTC, jmolmo commented
Closed in favor of #13

2021-12-09 12:14 UTC, closed without merging