feat: adds alerts for thin pool usage
red-hat-storage/lvm-operator pull request #151
Opened 2022-04-13 10:20 UTC by sp98

Adds alerts for thin pool data and metadata usage.
Provides near full (75%) and critical (85%) usage alerts.

Signed-off-by: Santosh Pillai <sapillai@redhat.com>

2022-04-20 10:05 UTC, nbalacha commented on config/prometheus/prometheus_rules.yaml
> +        "message": "Thin Pool data utilization in the VolumeGroup {{ $labels.device_class }} has crossed 8500 % on node {{ $labels.node }}. Free up some space or expand the thin pool immediately."
The message says it has crossed 8500%

2022-04-20 10:06 UTC, nbalacha commented on config/prometheus/prometheus_rules.yaml
> +        "message": "Thin Pool metadata utilization in the VolumeGroup {{ $labels.device_class }} has crossed 8500 % on node {{ $labels.node }}. Free up some space or expand the thin pool immediately.
Same as above.

2022-04-20 10:39 UTC, nbalacha requested changes
There seems to be an issue with the percentages displayed in the messages.

2022-04-20 10:41 UTC, aruniiird requested changes
Some values are not right. We have to correct it in the libsonnet file

2022-04-20 10:41 UTC, aruniiird commented on config/prometheus/prometheus_rules.yaml
> +        "message": "Thin Pool data utilization in the VolumeGroup {{ $labels.device_class }} has crossed 7500 % on node {{ $labels.node }}. Free up some space or expand the thin pool."
```suggestion
        "message": "Thin Pool data utilization in the VolumeGroup {{ $labels.device_class }} has crossed 75 % on node {{ $labels.node }}. Free up some space or expand the thin pool."
```

2022-04-20 10:41 UTC, aruniiird commented on config/prometheus/prometheus_rules.yaml
> +        "message": "Thin Pool data utilization in the VolumeGroup {{ $labels.device_class }} has crossed 8500 % on node {{ $labels.node }}. Free up some space or expand the thin pool immediately."
```suggestion
        "message": "Thin Pool data utilization in the VolumeGroup {{ $labels.device_class }} has crossed 85 % on node {{ $labels.node }}. Free up some space or expand the thin pool immediately."
```

2022-04-20 10:41 UTC, aruniiird commented on config/prometheus/prometheus_rules.yaml
> +        "message": "Thin Pool metadata utilization in the VolumeGroup {{ $labels.device_class }} has crossed 7500 % on node {{ $labels.node }}. Free up some space or expand the thin pool."
```suggestion
        "message": "Thin Pool metadata utilization in the VolumeGroup {{ $labels.device_class }} has crossed 75 % on node {{ $labels.node }}. Free up some space or expand the thin pool."
```

2022-04-20 10:41 UTC, aruniiird commented on config/prometheus/prometheus_rules.yaml
> +        "message": "Thin Pool metadata utilization in the VolumeGroup {{ $labels.device_class }} has crossed 8500 % on node {{ $labels.node }}. Free up some space or expand the thin pool immediately.
```suggestion
        "message": "Thin Pool metadata utilization in the VolumeGroup {{ $labels.device_class }} has crossed 85 % on node {{ $labels.node }}. Free up some space or expand the thin pool immediately."
```

2022-04-21 07:36 UTC, sp98 commented on config/prometheus/prometheus_rules.yaml
> +        "message": "Thin Pool metadata utilization in the VolumeGroup {{ $labels.device_class }} has crossed 8500 % on node {{ $labels.node }}. Free up some space or expand the thin pool immediately.
fixed. Also marking other similar comments are resolved.

2022-04-21 08:59 UTC, sp98 commented
/retest

2022-04-21 11:16 UTC, nbalacha commented on config/prometheus/prometheus_rules.yaml
> +        "message": "Thin Pool data utilization in the VolumeGroup {{ $labels.device_class }} has crossed 85 % on node {{ $labels.node }}. Free up some space or expand the thin pool immediately."
Was this generated by the jsonnet? I don't see any changes to the libsonnet file.

2022-04-21 15:00 UTC, merged