test: add lvm cluster CR deletion test
red-hat-storage/lvm-operator pull request #17
Opened 2021-12-10 10:51 UTC by leelavg

- use envtest for creation and deletion of lvm cluster CR
- refactor of existing unit test

Signed-off-by: Leela Venkaiah G <lgangava@redhat.com>

2021-12-10 10:56 UTC, nbalacha requested changes

2021-12-10 10:56 UTC, nbalacha commented on controllers/lvmcluster_controller_test.go
> +		It("should create an LVMCluster, ", func() {
The test should check that the reconcile succeeds on creation. It is not testing the LVMCluster creation itself.

2021-12-10 10:56 UTC, nbalacha commented on controllers/lvmcluster_controller_test.go
> +			By("indicating CR status to be ready after CR is deployed")
"Setting status.Ready to true on reconciliation"

2021-12-10 10:56 UTC, nbalacha commented on controllers/lvmcluster_controller_test.go
> +		It("should delete an LVMCluster, ", func() {
It should delete the resources on LVMCluster deletion.

2021-12-10 11:54 UTC, jmolmo commented
IMHO we are not testing the functionality of the controller. I mean we are just checking that  [controller runtime client](https://github.com/kubernetes-sigs/controller-runtime/tree/master/pkg/client) works properly using a CRD. And that is something [that has been already verified in the client package](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/example_test.go ).

I think that it has more meaning and utility for us the test proposed in #13, where after the creation of the lvmcluster CRD we verified the existence of the CSIDriver resource and topolvm deployment.

In any case ... is difficult for me to see this kind of test as "unit test" ,,, is more like a mix between integration test (without CI env) and "extended" unit tests.

2021-12-10 12:11 UTC, nbalacha commented on controllers/lvmcluster_controller_test.go
> +			By("confirming absence of lvm cluster CR")
The reconciliation does not delete the lvmCluster CR. The test should check that the LvmCluster deletion removes the other resources created by the operator.

2021-12-11 08:09 UTC, leelavg commented
> And that is something that has been already verified in the client package
- It was verified for an example resource creation, in our case we want to test creation of our CR with default spec for now and check status is true & reconciliation started and working as expected 

> I think that it has more meaning and utility for us the test proposed in #13
- the said pr will be split into three and this is the first one where I'm trying to create a layout for e2e-ish kind of flow and rest of 2 prs will build up on this layout

> In any case ... is difficult for me to see this kind of test as "unit test" ,,, is more like a mix between integration test (without CI env) and "extended" unit tests.
- yep, it's arguable, in a unit test-ish setup we have test spies, mocks/fakes etc however I don't want to stop moving forward to decide on how unit tests should look like at this point/pace of development 😅

IMHO, if we had flow charts then it suites better to commit failing tests first and then code to fix those tests

I'm open to suggestions on how good to refactor tests or what should be tested as part of unit tests and e2e tests.

Pls correct me if I presented something not relatable/right 😀

2021-12-15 07:30 UTC, nbalacha commented on controllers/lvmcluster_controller_test.go
> +	Context("LVMCluster reconciliation on installing CR", func() {
Reconciliation on creating an LVMCluster CR

2021-12-15 07:30 UTC, nbalacha commented on controllers/lvmcluster_controller_test.go
> +	Context("LVMCluster reconciliation on uninstalling CR", func() {
"reconciliation on deleting the LVMCluster CR"

2021-12-15 09:15 UTC, jmolmo approved these changes
I wonder is we can use the structure of this test to do all the "unit test"  for all the "functional units".
We need always to create the lvm cluster and start the reconcile loop, after that ,, the verification we need to do for each unit are basically the same ( the unit is created, deployed, and it is composed by several containers) .

2021-12-15 10:03 UTC, leelavg commented
@jmolmo yes, that's the plan. 

The current pr creates a basic skeleton and individual component owners add their units with their implementation.

2021-12-15 10:07 UTC, nbalacha approved these changes

2021-12-15 10:07 UTC, merged