[WIP] Add VGmanager daemonset, VGManager implementation
red-hat-storage/lvm-operator pull request #22
Opened 2021-12-13 10:53 UTC by rohantmp

Will be functional today, will update the PR when it is. Basic structure is in place.

Pseudocode comments are in place and some functions are empty

2021-12-14 06:59 UTC, rohantmp commented
I think it's ready for review, but I can't test latest changes because of build issues.

2021-12-14 08:01 UTC, leelavg reviewed
- didn't review `internal` and some of the pkgs in `vgmanager`

2021-12-15 16:34 UTC, rohantmp commented on controllers/vgmanager.go
> +	if result != controllerutil.OperationResultNone {
this logs everything other than operationresultnone

2021-12-15 17:55 UTC, rohantmp commented
That should do it. Lacks polish and unit-testing, but I've run out of time.

 I've left todo(rohan) comments wherever I couldn't get to things in time.

Here's a demo of things in action: https://asciinema.org/a/nmhZQYXgTLG3oSOxE0ROD8vlX

2021-12-16 02:27 UTC, rohantmp commented on Dockerfile.vgmanager
> +FROM gcr.io/distroless/static:nonroot
switched to centos

2021-12-17 13:41 UTC, nbalacha requested changes

2021-12-24 07:04 UTC, leelavg commented
- Parts of this PR #26 and #27 is merged and so closing this.

2021-12-24 07:04 UTC, closed without merging