Refactor vgmanager
red-hat-storage/lvm-operator pull request #59
Opened 2022-01-05 07:58 UTC by sp98

- Add

2022-01-11 16:02 UTC, nbalacha requested changes
First round of review. I'll do one more round tomorrow.

2022-01-12 14:17 UTC, sp98 commented on pkg/vgmanager/vgmanager_controller.go
> +		return fmt.Errorf("can't create vg with 0 devices")
done.

2022-01-12 14:17 UTC, sp98 commented on pkg/vgmanager/lvm.go
> +		return nil, fmt.Errorf("failed to unmarhsal volume group response. %v", err)
done

2022-01-12 14:17 UTC, sp98 commented on pkg/vgmanager/lvm.go
> +	volumeGroupMap := map[string][]map[string][]VolumeGroup{}
done

2022-01-12 14:17 UTC, sp98 commented on pkg/vgmanager/vgmanager_controller.go
> +	args := []string{vgName}
done.

2022-01-12 16:39 UTC, nbalacha commented
Please correct the commit messages (formats)

2022-01-13 05:01 UTC, nbalacha approved these changes

2022-01-13 05:01 UTC, merged