Add install and usage doc
red-hat-storage/lvm-operator pull request #84
Opened 2022-01-20 13:14 UTC by mulbc

2022-01-24 06:17 UTC, nbalacha approved these changes

2022-01-24 06:18 UTC, nbalacha requested changes
Please change the commit message to include a subject or combine the 2 commits into one.

2022-01-27 15:52 UTC, nbalacha requested changes
Please remove the changes to config/manager/kustomization.yaml and controllers/topolvm_controller.go from the PR.

2022-01-27 16:49 UTC, mulbc commented
one git commit --all --ammend too often -.- fixed now :)

2022-01-28 08:12 UTC, nbalacha approved these changes

2022-01-28 08:12 UTC, merged